#!/bin/sh
echo "*****************************************************"
if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
  PL=1
fi
if [ -f /media/hdd/STARTUP ] && [ -f /media/hdd/linuxrootfs20/zImage ]  ; then
    LocationImg=/media/hdd
elif [ -f /media/usb/STARTUP ] && [ -f /media/usb/linuxrootfs20/zImage ]  ; then    
    LocationImg=/media/usb
fi
if [ -f /boot/STARTUP_RECOVERY ] && [ -f ${LocationImg}/linuxrootfs20/zImage ] ; then
    sleep 1
    echo "kernel=/linuxrootfs20/zImage root=/dev/sda1 rootsubdir=linuxrootfs20" > /boot/STARTUP
    [ $PL ] && echo "Restart systemu !" || echo "Reboot system !"
    echo " ";
    echo "*****************************************************";
    sleep 2
    /etc/init.d/reboot    
else
    [ $PL ] && echo "Slot 20 jest pusty !" || echo "Slot 20 is empty !"
    echo " "
fi
exit 0